name: ✨ Feature Request
description: Suggest a new feature for LineupTracker
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        
        Before submitting, please:
        - Search existing issues to see if this has been requested
        - Consider if this fits the project's scope and goals
        - Think about how this would benefit other users

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Core Monitoring System
        - Notifications & Alerts
        - Web Dashboard
        - Squad Management
        - API & Data Sources
        - Configuration & Setup
        - Mobile/Desktop App
        - Analytics & Reporting
        - Multi-League Support
        - AI/ML Features
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve? 
        Describe the current limitation or pain point.
      placeholder: |
        Currently, users have to...
        This makes it difficult to...
        It would be much better if...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your proposed solution in detail.
        How should this feature work?
      placeholder: |
        I propose adding...
        It would work by...
        Users would be able to...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: |
        Have you considered any alternative approaches?
        What other ways could this problem be solved?
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        I prefer the main solution because...

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: |
        Write 1-3 user stories to help us understand the feature from a user's perspective
      placeholder: |
        As a fantasy football manager, I want to... so that I can...
        As a casual user, I want to... so that I can...
        As a power user, I want to... so that I can...

  - type: checkboxes
    id: target-users
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      options:
        - label: New users (ease of setup)
        - label: Casual fantasy players
        - label: Serious fantasy players
        - label: Multi-league managers
        - label: Technical users
        - label: Mobile users
        - label: Dashboard users

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/blocking issue
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas (Optional)
      description: |
        If you have technical knowledge, share any implementation ideas or considerations.
        This helps us understand the scope and complexity.
      placeholder: |
        This could be implemented by...
        It might require changes to...
        Consider these technical challenges...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd like to help implement this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback and requirements

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, mockups, or examples that help explain the feature.
        
        You can attach files or paste images here.
